Add package to ClassToken
acout/scala-retro pull request #3
Opened 2020-12-08 09:38 UTC by riiswa

2020-12-15 10:13 UTC, riiswa commented on core/src/main/scala/com/github/acout/scala-retro/Utils.scala
> +                d.listFiles.filter(_.isFile).toList.filter(_.getName.endsWith(".scala")) ++ d.listFiles.filter(_.isDirectory).flatMap(d => getAllScalaFiles(d.toPath))
Ajout du filtre pour récupérer uniquement les fichiers .scala

2020-12-15 10:14 UTC, riiswa commented on core/src/main/scala/com/github/acout/scala-retro/token/Token.scala
Extension du trait Encapsulation: ajout d'une représentation pour les préfixe d'encapsulation en UML

2020-12-15 10:17 UTC, riiswa commented on core/src/main/scala/com/github/acout/scala-retro/token/Token.scala
>  case class Attribute(name: String, t: String, encapsulation: Encapsulation)
Ajout de l'encapsulation pour les méthodes

2020-12-15 10:17 UTC, riiswa commented on core/src/main/scala/com/github/acout/scala-retro/token/Token.scala
> +
Ajout d'un trait spécifiant le type de classe : class, trait ou object

2020-12-15 10:18 UTC, riiswa commented on core/src/main/scala/com/github/acout/scala-retro/token/Token.scala
>  sealed trait Token
Ajout du package et du type de class à ClassToken

2020-12-15 10:20 UTC, riiswa commented on core/src/main/scala/com/github/acout/scala-retro/tokenizer/ScalaTokenizer.scala
> +
Obtenir récursivement des informations sur l'encapsulation d'un item, sans spécification particulaire l'item est par défaut public

2020-12-15 10:23 UTC, riiswa commented on core/src/main/scala/com/github/acout/scala-retro/tokenizer/ScalaTokenizer.scala
> +
Amélioration de la méthode tokenize :
- Filtrage des dépendances avec des objets non présent dans le package, par exemple List, Option, Int, String etc
- Reformatage des dépendances, dorénavant `List[X`], `X`, et `X[Y]`, mèneront tous à des dépendances vers `X`

2020-12-15 10:23 UTC, riiswa commented on core/src/main/scala/com/github/acout/scala-retro/tokenizer/ScalaTokenizer.scala
>                  }
Ajout des objets

2020-12-15 10:23 UTC, riiswa commented on core/src/main/scala/com/github/acout/scala-retro/tokenizer/ScalaTokenizer.scala
>                          }
Ajout des objets

2020-12-15 10:24 UTC, riiswa commented on core/src/main/scala/com/github/acout/scala-retro/tokenizer/ScalaTokenizer.scala
>                      case c: Defn.Class => {
Spécification des packages, si l'information est attendu en sortie

2020-12-15 10:25 UTC, riiswa commented on core/src/main/scala/com/github/acout/scala-retro/tokenizer/ScalaTokenizer.scala
Spécification des packages dans les méthodes de tokenization

2020-12-15 10:27 UTC, riiswa commented on core/src/main/scala/com/github/acout/scala-retro/tokenizer/ScalaTokenizer.scala
>          val hasDefs = !c.templ.stats.filter(_.isInstanceOf[Defn.Def]).isEmpty
Ajout des attributs du constructeurs, par exemple pour les case class et pour les champs expliciter comme val

2020-12-15 10:28 UTC, riiswa commented on core/src/main/scala/com/github/acout/scala-retro/tokenizer/ScalaTokenizer.scala
> +        // Add support for all types of attributes
Support pour tout type d'attribut : 
- var x = X
-var x: X
- val x = X
-val x: X

2020-12-15 10:29 UTC, riiswa commented on core/src/main/scala/com/github/acout/scala-retro/tokenizer/ScalaTokenizer.scala
>              })
Encapsulation pour les méthodes

2020-12-15 10:29 UTC, riiswa commented on core/src/main/scala/com/github/acout/scala-retro/tokenizer/ScalaTokenizer.scala
>              if(hasTParams){
Ajout des attributs de constructeurs

2020-12-15 10:30 UTC, riiswa commented on core/src/main/scala/com/github/acout/scala-retro/tokenizer/ScalaTokenizer.scala
>          })
Ajout des constructeurs d'attributs

2020-12-15 10:30 UTC, riiswa commented on core/src/main/scala/com/github/acout/scala-retro/tokenizer/ScalaTokenizer.scala
Modification similaires aux classes pour les traits (sans les paramètres de constructeurs)

2020-12-15 10:31 UTC, riiswa commented on core/src/main/scala/com/github/acout/scala-retro/tokenizer/ScalaTokenizer.scala
Method similaire aux traits pour la tokénization des objets

2020-12-15 10:32 UTC, riiswa commented on core/src/main/scala/com/github/acout/scala-retro/writer/MermaidClassDiagramHTMLWriter.scala
>    private val htmlTemplateHeader: String = s"""<html>
Fix de la taille de la box meirmaid lors de la génération de l'HTML

2020-12-15 10:32 UTC, riiswa commented on core/src/main/scala/com/github/acout/scala-retro/writer/MermaidClassDiagramWriter.scala
Support des caractères d'échappement Meirmaid pour la génération de l'HTML

2020-12-15 10:35 UTC, riiswa commented on core/src/main/scala/com/github/acout/scala-retro/writer/MermaidClassDiagramWriter.scala
>          token match {
Ajout du type de classe au DIagramme

2020-12-15 10:35 UTC, riiswa commented on core/src/main/scala/com/github/acout/scala-retro/writer/MermaidClassDiagramWriter.scala
>                  }
Echappement des caractères > et <

2020-12-15 10:35 UTC, riiswa commented on core/src/main/scala/com/github/acout/scala-retro/writer/MermaidClassDiagramWriter.scala
>              val lastIndex = str.lastIndexOf("]")
Correction du Bug qui affiche List<List_X_> au lieu de List<List<X>>

2020-12-15 10:49 UTC, acout commented on core/src/main/scala/com/github/acout/scala-retro/token/Token.scala
J'ai un souci avec cette modification car elle mélange tokenisation et représentation.

2020-12-15 10:51 UTC, acout commented on core/src/main/scala/com/github/acout/scala-retro/token/Token.scala
> +
Même remarque : mélange de la tokenisation et de la représentation. Ce n'est pas souhaitable.

2020-12-15 10:59 UTC, acout commented on core/src/main/scala/com/github/acout/scala-retro/writer/MermaidClassDiagramWriter.scala
>                  }
Attention du coup à l'usage de représentations définies dans les Token. Il faudrait dissocier les 2, via des fonctions qui transforment des Token en la bonne représentation, comme pour le reste.

2020-12-15 10:59 UTC, acout commented on core/src/main/scala/com/github/acout/scala-retro/writer/MermaidClassDiagramWriter.scala
>              val lastIndex = str.lastIndexOf("]")
Attention du coup à l'usage de représentations définies dans les Token. Il faudrait dissocier les 2, via des fonctions qui transforment des Token en la bonne représentation, comme pour le reste.

2020-12-15 11:00 UTC, acout requested changes
Les ajouts sont très intéressants et pertinents. Juste un bémol concernant le mélange de tokenisation et de représentation, qui ne correspond pas à la philosophie de la segmentation entre ces deux étapes dans le projet.

2021-03-06 10:04 UTC, acout approved these changes

2021-03-06 10:04 UTC, merged